### ISSUE TITLE
Documentation is a bit confusing when referring to user variables and the "kernel"

### ISSUE THREAD

**Issue by SamCoVT** [SamCoVT/TaliForth2#25]
The documentation calls label "user0" the User and System variables, while there are also User Variables at the beginning of the dictionary.  Perhaps denoting them as "Zero-Page User and System Variables" and "Dictionary User Variables" might make sense, as both locations contain user variables.

I'd like to leave the labels alone, so as not to break existing usages, and just update the descriptions of each to be more clear.

**Comment by patricksurry** [comment]
this tangentially relates to my confusion about whether space labeled as "kernel" is reserved by tali, or free for external code (kernel) to use.  i'm also confused by what user means in this context.

**Comment by SamCoVT** [comment]
Just FYI, the whole idea of user variables is to support cooperative multitasking (not yet implemented).  Each thread of execution would have it's own environment, so that one might be interpreting out of block storage, while another is running from a serial port, while another is accepting input from the keyboard.  They can't share a resource (like the keyboard), but can use resources that the others are not using.  The user can also store their own values in that separate environment (that's the "user" part) so that each of these threads can have a different value for the same variable.  This makes task switching as easy as updating the `up` (User Pointer) to the correct environment for the next task and then jumping into that task.

If variables are placed in the regular dictionary (before a new thread is started, so that it is visible in that thread's dictionary), then they are shared and can be used to communicate between threads with some care.  Only one thread can be compiling, but the others can interpret all they want.

I do not currently have plans to implement multitasking, but some of the legwork was done to make it easier to implement.  It probably makes sense to rename these just to eliminate the confusion.

Perhaps "System Variables" is a better name instead of "User Variables".

Do you think "User's Kernel" or "User Provided Kernel" or maybe even just "Available" is better for the kernel confusion?

**Comment by patricksurry** [comment]
maybe "taliforth system variables" ? user seems more ambiguous.  

available sounds good to me.
