### ISSUE TITLE
c65 doesn't end on BYE

### ISSUE THREAD

**Issue by SamCoVT** [SamCoVT/TaliForth2#76]
Tali's default behavior on `BYE` is to run the `BRK` instruction.  This drops py65mon back to the simulator prompt.  In c65, it just resets Tali (because Tali's start vector is placed in all three vectors at the end of memory).  If c65 can be modified to terminate on BRK (perhaps with a command line option?) then then Tali's startup message of "Type 'bye' to exit" will work for both py65mon and c65.  With c65, I'd expect it to fully terminate and just drop back to a prompt.

**Comment by patricksurry** [comment]
that sounds doable; you can assign to me

**Comment by patricksurry** [comment]
This would also be a good excuse to remove the 'shutdown' action in the block IO device which is basically the same
