### ISSUE TITLE
document that kernel_getc/putc must preserve X,Y

### ISSUE THREAD

**Issue by patricksurry** [SamCoVT/TaliForth2#84]
This tripped me up while putting Tali on some breadboard hardware.  My LCD `putc` was mangling Y but `emit_a`/`key_a` assume X and Y are unchanged.   Strange results ensued.  Maybe just a good comment in the platform file would work.

**Comment by SamCoVT** [comment]
That's a good point.  `spaces` has already been modified to reload A to accommodate `kernel_putc` that destroys A (I think that was the only word that was using `kernel_putc` in a loop and originally it only loaded the space once).  Updating the comments in the platform file makes the most sense.
